# Generated by Django 5.0.4 on 2024-04-16 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giocatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100, verbose_name='Nome del giocatore')),
                ('player_key', models.CharField(max_length=50, unique=True, verbose_name='Chiave univoca del giocatore')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('tournament_key', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('superficie', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.IntegerField(unique=True, verbose_name="Chiave univoca dell'evento")),
                ('event_date', models.DateField(verbose_name="Data dell'evento")),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name="Ora dell'evento")),
                ('event_first_player', models.CharField(max_length=50, verbose_name='Primo giocatore')),
                ('event_second_player', models.CharField(max_length=50, verbose_name='Secondo giocatore')),
                ('event_final_result', models.CharField(max_length=15, verbose_name='Risultato finale')),
                ('event_winner', models.CharField(blank=True, choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Secondo giocatore')], max_length=15, null=True, verbose_name="Vincitore dell'evento")),
                ('event_status', models.CharField(max_length=50, verbose_name="Stato dell'evento")),
                ('event_type_type', models.CharField(max_length=50, verbose_name='Tipo di evento')),
                ('tournament_name', models.CharField(max_length=100, verbose_name='Nome del torneo')),
                ('tournament_round', models.CharField(max_length=50, null=True, verbose_name='Round del torneo')),
                ('tournament_season', models.CharField(max_length=4, verbose_name='Stagione del torneo')),
                ('event_live', models.CharField(choices=[('0', 'No'), ('1', 'Sì')], max_length=1, verbose_name='Evento dal vivo')),
                ('event_qualification', models.BooleanField(default=False, verbose_name="Qualificazione all'evento")),
                ('first_player_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_first_player', to='tennisxchange.giocatore', verbose_name='Chiave univoca del primo giocatore')),
                ('second_player_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_second_player', to='tennisxchange.giocatore', verbose_name='Chiave univoca del secondo giocatore')),
                ('tournament_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennisxchange.torneo', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Partita',
                'verbose_name_plural': 'Partite',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_first', models.CharField(max_length=10, verbose_name='Punteggio Primo Giocatore')),
                ('score_second', models.CharField(max_length=10, verbose_name='Punteggio Secondo Giocatore')),
                ('score_set', models.CharField(max_length=10, verbose_name='Numero del Set')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='tennisxchange.match', verbose_name='Match')),
            ],
            options={
                'verbose_name': 'Set',
                'verbose_name_plural': 'Set',
                'unique_together': {('match', 'score_set')},
            },
        ),
    ]
