# Generated by Django 5.0.4 on 2024-04-17 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_game', models.CharField(max_length=10, verbose_name='Numero del Gioco')),
                ('player_served', models.CharField(blank=True, choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Secondo giocatore'), ('Tiebreak', 'Tiebreak')], max_length=50, null=True, verbose_name='Giocatore al Servizio')),
                ('serve_lost', models.CharField(blank=True, choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Secondo giocatore'), (None, 'Servizio mantenuto')], max_length=50, null=True, verbose_name='Servizio perso')),
                ('game_winner', models.CharField(choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Secondo giocatore')], max_length=50, verbose_name='Vincitore del Gioco')),
                ('set_score', models.CharField(max_length=10, verbose_name='Punteggio del Set')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tennisxchange.set', verbose_name='Set')),
            ],
            options={
                'verbose_name': 'Gioco',
                'verbose_name_plural': 'Giochi',
                'unique_together': {('set', 'number_game')},
            },
        ),
    ]
