# Generated by Django 5.0.4 on 2024-04-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0002_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
