# Generated by Django 5.0.4 on 2024-04-17 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0005_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_game', models.IntegerField(blank=True, null=True)),
                ('player_served', models.CharField(choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Secondo giocatore')], max_length=100)),
                ('serve_lost', models.CharField(blank=True, max_length=100, null=True)),
                ('game_winner', models.CharField(choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Secondo giocatore')], max_length=100)),
                ('set_score', models.CharField(max_length=10)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tennisxchange.set')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'unique_together': {('set', 'number_game')},
            },
        ),
    ]
