# Generated by Django 5.0.4 on 2024-04-19 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0006_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_point', models.IntegerField(verbose_name='Numero progressivo del punto')),
                ('break_point', models.CharField(choices=[('yes', 'Sì'), ('no', 'No')], default='no', max_length=3, verbose_name='Break Point')),
                ('game_score', models.CharField(max_length=10, verbose_name='Punteggio del Game')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tennisxchange.game')),
            ],
            options={
                'verbose_name': 'Punto',
                'verbose_name_plural': 'Punti',
                'unique_together': {('game', 'number_point')},
            },
        ),
    ]
