# Generated by Django 5.0.4 on 2024-04-20 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0007_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiebreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_first_player', models.CharField(max_length=10, verbose_name='Punteggio finale primo giocatore')),
                ('score_second_player', models.CharField(max_length=10, verbose_name='Punteggio finale secondo giocatore')),
                ('set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tiebreak', to='tennisxchange.set', verbose_name='Set associato')),
            ],
            options={
                'verbose_name': 'Tiebreak',
                'verbose_name_plural': 'Tiebreaks',
            },
        ),
        migrations.CreateModel(
            name='TiebreakPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_number', models.IntegerField(verbose_name='Numero del punto')),
                ('player_served', models.CharField(choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Secondo giocatore')], max_length=100, verbose_name='Giocatore al servizio')),
                ('point_winner', models.CharField(choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Secondo giocatore')], max_length=100, verbose_name='Vincitore del punto')),
                ('serve_lost', models.CharField(blank=True, max_length=100, null=True, verbose_name='Servizio perso da')),
                ('score', models.CharField(max_length=10, verbose_name='Punteggio del punto')),
                ('tiebreak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tennisxchange.tiebreak', verbose_name='Tiebreak')),
            ],
            options={
                'verbose_name': 'Punto del Tiebreak',
                'verbose_name_plural': 'Punti del Tiebreak',
                'unique_together': {('tiebreak', 'point_number')},
            },
        ),
    ]
