# Generated by Django 5.0.4 on 2024-04-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0008_tiebreak_tiebreakpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='event_qualification',
            field=models.BooleanField(default=None, null=True, verbose_name="Qualificazione all'evento"),
        ),
    ]
