# Generated by Django 5.0.4 on 2024-04-24 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0009_alter_match_event_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_period', models.CharField(default='match', max_length=50, verbose_name='Periodo della statistica')),
                ('stat_type', models.CharField(max_length=50, verbose_name='Tipo di statistica')),
                ('stat_name', models.CharField(max_length=100, verbose_name='Nome della statistica')),
                ('stat_value', models.CharField(max_length=50, verbose_name='Valore della statistica')),
                ('stat_won', models.IntegerField(blank=True, null=True, verbose_name='Statistiche vinte')),
                ('stat_total', models.IntegerField(blank=True, null=True, verbose_name='Statistiche totali')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tennisxchange.match', verbose_name='Partita')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tennisxchange.giocatore', verbose_name='Giocatore')),
            ],
            options={
                'verbose_name': 'Statistica del Match',
                'verbose_name_plural': 'Statistiche dei Match',
                'unique_together': {('match', 'player', 'stat_name', 'stat_period')},
            },
        ),
    ]
