# Generated by Django 5.0.4 on 2024-04-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0010_matchstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Quota del Secondo Giocatore (bet365)'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Quota del Primo Giocatore (bet365)'),
        ),
    ]
