# Generated by Django 5.0.4 on 2024-04-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0011_match_away_odds_match_home_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_served',
            field=models.CharField(blank=True, choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Secondo giocatore')], max_length=100, null=True),
        ),
    ]
