# Generated by Django 5.0.4 on 2024-04-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0012_alter_game_player_served'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_served',
            field=models.CharField(choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Secondo giocatore')], max_length=100),
        ),
    ]
