# Generated by Django 5.0.4 on 2024-05-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0013_alter_game_player_served'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo di statistica')),
                ('name', models.CharField(max_length=100, verbose_name='Nome della statistica')),
            ],
            options={
                'verbose_name': 'Tipo di Statistica',
                'verbose_name_plural': 'Tipi di Statistiche',
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='matchstat',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='matchstat',
            name='stat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennisxchange.stattype', verbose_name='Tipo e nome della statistica'),
        ),
        migrations.AlterUniqueTogether(
            name='matchstat',
            unique_together={('match', 'player', 'stat_type', 'stat_period')},
        ),
        migrations.RemoveField(
            model_name='matchstat',
            name='stat_name',
        ),
    ]
