# Generated by Django 5.0.4 on 2024-05-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0014_stattype_alter_matchstat_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstat',
            name='stat_type',
            field=models.CharField(max_length=50, verbose_name='Tipo di statistica'),
        ),
        migrations.AlterUniqueTogether(
            name='matchstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matchstat',
            name='stat_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome della statistica'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='matchstat',
            unique_together={('match', 'player', 'stat_name', 'stat_period')},
        ),
        migrations.DeleteModel(
            name='StatType',
        ),
    ]
