# Generated by Django 5.0.4 on 2024-05-12 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0016_alter_matchstat_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tennisxchange.giocatore', verbose_name='Giocatore'),
        ),
    ]
