# Generated by Django 5.0.4 on 2024-05-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0017_alter_matchstat_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point_winner',
            field=models.CharField(blank=True, choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Secondo giocatore')], max_length=100, null=True, verbose_name='Vincitore del punto'),
        ),
    ]
