# Generated by Django 5.0.4 on 2024-05-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisxchange', '0018_point_point_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiebreakpoint',
            name='player_served',
            field=models.CharField(choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Second giocatore')], max_length=100, verbose_name='Giocatore al servizio'),
        ),
        migrations.AlterField(
            model_name='tiebreakpoint',
            name='point_winner',
            field=models.CharField(choices=[('First Player', 'Primo giocatore'), ('Second Player', 'Second giocatore')], max_length=100, verbose_name='Vincitore del punto'),
        ),
    ]
